# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: walk_command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12walk_command.proto\"G\n\x0bWalkCommand\x12\x10\n\x08target_x\x18\x01 \x01(\x02\x12\x10\n\x08target_y\x18\x02 \x01(\x02\x12\x14\n\x0ctarget_theta\x18\x03 \x01(\x02\"B\n\x0f\x43\x61meraImageData\x12\x0e\n\x06height\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x10\n\x08raw_data\x18\x03 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'walk_command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WALKCOMMAND._serialized_start=22
  _WALKCOMMAND._serialized_end=93
  _CAMERAIMAGEDATA._serialized_start=95
  _CAMERAIMAGEDATA._serialized_end=161
# @@protoc_insertion_point(module_scope)
